### ISSUE TITLE
Always compares to main branch

### ISSUE THREAD

**Issue by thclark** [octue/conventional-commits#16]
### What is the current behavior?

If I have branches

`main -> dev -> myfeature`

And I use
```
on: pull_request
```
in my GHA, and make a pull request into a `dev` from `myfeature`, the contents of `myfeature` are compared to the contents of `main`, not to the contents of `dev`, so the PR summary contains all of the work in main.

### What is the expected behavior?

It should compare to the base branch, not the main branch.

**Comment by cortadocodes** [comment]
Have you merged `main` into your branch? The commit messages are picked straight from the git log up until the latest tag. If that tag isn't present on the branch, it'll pick up more commits than it should.

**Comment by cortadocodes** [comment]
Also which repo is this occurring for you on?

**Comment by cortadocodes** [comment]
This may be solved by #17

**Comment by thclark** [comment]
![image](https://user-images.githubusercontent.com/7223170/129176923-f1555b8a-3a07-437b-bd5b-df2f8ec230be.jpg)

Image to clarify what I mean. I’ve not checked if this is solved yet but I think perhaps not since the feature/epic branch wouldn’t have a tag after Commit 2 in this diagram?

**Comment by cortadocodes** [comment]
I think what will happen at the moment is that:
* `feature/epic` will have commits 1 and 2 in its PR description
* `feature/sub` will have commits 1, 2, 3, and 4 in its PR description
* When `feature/sub` is merged into `feature/epic`, `feature/epic`'s PR description will then contain commits 1, 2, 3, and 4
* When `feature/epic` is then merged into `main`, the release notes will contain commits 1, 2, 3, and 4

I guess what we want is the above except that `feature/sub` should only have commits 3 and 4 in its PR? I think I can update the code to do this.
