### ISSUE TITLE
Semver checker fails due to branch name inclusion

### ISSUE THREAD

**Issue by thclark** [octue/conventional-commits#29]
### What is the current behavior?

Semantic version checker fails because it thinks the version should have the branch and sha appended.

In [this check run](https://github.com/windpioneers/power-curve-utilities/pull/50/checks?check_run_id=3632464026) in which branch `feature/add-gw-nordex-ge-turbines` is being merged into `main` the failure is as follows:
```
The current version (0.1.0) is different from the expected semantic version (0.1.0+feature-add-gw-nordex-ge-turbines.e5a8956).
```

### What is the expected behavior?

With the version at 0.1.0 I expected that to pass correctly.

**Comment by cortadocodes** [comment]
Is the `mkver.conf` file present on that branch? I can't access the branch for some reason

**Comment by cortadocodes** [comment]
@thclark I've just re-run the above check with the new verson of `conventional-commits` and the following error is now raised. You just need to include a `mkver.conf` file that's correctly set up for whichever file contains the package version.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/bin/check-semantic-version", line 33, in <module>
    sys.exit(load_entry_point('conventional-commits==0.2.2', 'console_scripts', 'check-semantic-version')())
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/conventional_commits/check_semantic_version.py", line 71, in main
    raise FileNotFoundError(
FileNotFoundError: A mkver.conf file is required in the current working directory (usually the repository root) in order to check the semantic version.
```

**Comment by thclark** [comment]
Beautiful, thanks @cortadocodes
