### ISSUE TITLE
Mkver comparison incorrect where package.json not in repository root

### ISSUE THREAD

**Issue by thclark** [octue/conventional-commits#47]
### What is the current behavior?
I'm using a subpackage in a repository which is versioned on a non-standard file path; i.e. `packages/components/package.json`. There is also a `package.json` in the root directory (with no version information).

I have a `main` branch in which the version is presently `0.11.0` and a pull request into that, with several commits, whose version is still `0.11.0`.

The semantic version check is passing, and stating that the version `0.11.0` is as expected (i.e. it is reading the correct file to determine the current version).

However the presence of additional patch commits suggests it should be `0.11.1`.

Reproduction is at [this point in the tree](https://github.com/windpioneers/component-library/tree/687e8d7194c8bb8ef7c773650800b4597b53d151) for [this PR](https://github.com/windpioneers/component-library/pull/243).

### What is the expected behavior?

The checker should fail and indicate that I should be at `0.11.1`. I suspect that it's comparing
 -  `[branch] packages/components/package.json` to `[main] package.json` instead of comparing 
 - `[branch] packages/components/package.json` to `[main] packages/components/package.json`

### Other information

Now that I think about it, I'm not sure it's possible to even support independently versioned subpackages at all. Perhaps we need to simply accept that the version must be dictated and if a top-level package.json exists that the version be specified in there.

To be discussed.

**Comment by cortadocodes** [comment]
The semantic version check for the **next** version works by looking at the conventional commits since the most recent semantic version tag. As there can only be one latest semantic version of a given git repository, `git-mkver` can only predict what this will be. It doesn't compare `main` to the current branch so, as far as I'm aware, can't keep track of subpackage versioning. The use case above would of course be possible but we'd have to re-engineer things a bit.

**Comment by cortadocodes** [comment]
I've looked into this further and the problem was actually just that the `mkver.conf` file was wrong. I think I created it before we understood how to properly control `git-mkver`. I'm fixing it now

**Comment by cortadocodes** [comment]
Solved in https://github.com/windpioneers/component-library/pull/245
