### ISSUE TITLE
Consider using ❌  or similar emoji to denote breaking changes

### ISSUE THREAD

**Issue by cortadocodes** [octue/conventional-commits#60]
This might make release notes a bit more readable and make it easier for breaking changes to stand out. It can be [a bit hard to see them currently](https://github.com/octue/octue-sdk-python/pull/402).

**Comment by thclark** [comment]
I'm a big fan of this idea. Like you I hate gitmoji in general but where they could make meaning clearer I'm into it.

I think we should talk about the icons we use though because the X looks like a failure. We may choose a limited extra subset. Can we postpone until I'm back?

**Comment by cortadocodes** [comment]
Cool cool. Maybe this would work better: 🅱️

**Comment by cortadocodes** [comment]
Other emoji candidates: 🚨 💥 ❗ ⚠️
